### ISSUE TITLE
The Windows Image did not download properly

### ISSUE THREAD

**Issue by iamacarpet** [OSDeploy/OSDCloud#10]
Hello!

Thanks for the great product, it's been amazing to use so far, very impressed.

We've hit a bit of a brick wall:

Exactly the same WinPE image & config, worked beautifully last week, but this week is throwing an error reliably every time we try and use it:

`The Windows Image did not download properly`

![image](https://user-images.githubusercontent.com/1333857/169798691-a72369ac-4d22-4c32-b09a-69915128de5e.png)

The `.esd` file has downloaded though, correctly, in the right place: I can even run `Extract-WindowsImage` and expand it manually.

I've tried running all the commands from the source of `Invoke-OSDCloud.ps1` that handle the download & run immediately after it before the error block that is being printed manually to see where it's going wrong, but as far as I can tell, all the commands individually return the right stuff.

I'm running with:

```
Start-OSDCloud -Firmware -SkipAutopilot -SkipODT -ZTI -OSVersion "Windows 11" -OSBuild "21H2" -OSEdition "Pro" -OSLanguage "en-gb" -OSLicense "Retail"
```

Here is the file showing in the right place on disk, successful download, different run though so timestamps won't match the first screenshot:

![image](https://user-images.githubusercontent.com/1333857/169799993-02b866fc-6c38-4a88-9dad-8d1c44ab4507.png)

I've tried completely flattening the disk to make sure nothing was persisting between boots that could be causing problems, didn't seem to make any difference.

Is anyone else experiencing issues like this?

Regards,
iamacarpet

**Comment by richardsevern** [comment]
[glazier.log](https://github.com/OSDeploy/OSDCloud/files/8753918/glazier.log)
Log file from an attempted install with the same error.

Thanks
Richard

**Comment by iamacarpet** [comment]
I've just had confirmation from our wider team that this is the same across different machines inc. different models:

Thanks @richardsevern

Something broken in OSD [22.5.23.1](https://www.powershellgallery.com/packages/OSD/22.5.23.1) that went live 4 hours ago?

I will try to confirm that now by seeing if I can roll back the version inside WinPE after it updates on boot.

**Comment by iamacarpet** [comment]
Thanks to @richardsevern , we've both been able to confirm it is only broken in the latest version of OSD.

Downgrading to the previous version fixes things.

@OSDeploy FYI

**Comment by iamacarpet** [comment]
Looks like this was fixed in https://github.com/OSDeploy/OSD/commit/0ee5e1bfff96d865392c25923656e72d5b8c8a6b

PowerShell Gallery: https://www.powershellgallery.com/packages/OSD/22.5.23.2

Thank you @OSDeploy , appreciate the quick fix!!
