### ISSUE TITLE
WinPE Boot Cycle

### ISSUE THREAD

**Issue by Harry3co** [OSDeploy/OSDCloud#29]
Hi 
I try to test OSD Cloud deployment on a VM, i created a OSDCloud Workspace and replaced also the boot.wim of the ADK directory.
When i boot on a VM with the created ISO in my Workspace, i am able to Start the OSDCloudGUI and choose
an Operating System and Drivers aswell, i go for Microsoft Catalog since it's a VM. Everything seems to install well, but after the Restart
it just boots into the WinPE Startup Screen again, it doesn't boot into OOBE or Windows even.
What am i missing?
Thanks for any help in advance.

**Comment by Dirk-Manderin** [comment]
Do you have the boot order for your VM set to always boot from CD first?

**Comment by Harry3co** [comment]
Hey 
I just realised that my vm was set to BIOS, even when in my task sequence has a bios format step, for some reasons it does not recognize it as BIOS, so it was formatting always UEFI, which obvisously does not work on boot. 
I don't know why it's not recognizing BIOS, anyhow since i switched to EFI it's working as a charm. 
Sorry for that beginners mistake, and for your help.
